# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

os: linux
sudo: required
services: docker
language: generic

env:
  global:
    - bionic="ubuntu:bionic"
    - artful="ubuntu:artful"
    - xenial="ubuntu:xenial"
    - cosmic="ubuntu:cosmic"
  matrix:
    - D=bionic I=checks,up
    - D=bionic I=appimage,up            # gcc
    - D=bionic I=clang,distcheck
    - D=artful I=gcc
    - D=xenial I=gcc
    # upcoming releases
    - D=cosmic I=gcc
    #- D=debian:unstable    I=gcc
    #- D=debian:unstable    I=clang
matrix:
  allow_failures:
    - env: D=cosmic I=gcc
    #- env: D=debian:unstable    I=gcc
    #- env: D=debian:unstable    I=clang
  fast_finish: true

before_install:
  # Show build setup
  - echo "D=$D I=$I"
  - uname -a
  - cat /etc/os-release

install:
  - env | grep '^AUTHSECRET_\w\+=' >.secrets && unset `sed 's/=.*//' .secrets` || true
  # git describe requires complete history
  - travis_retry git fetch --unshallow

script:
  # Build inside docker container
  - TZ=GMT date
  - docker build -f misc/Dockerfile-apt --build-arg DIST="${!D}" --build-arg INTENT="$I" -t beast-ci .
  - docker ps -a

after_success:
  - echo "OK, all done."

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
    on_success: always
    on_failure: always
    skip_join: true
  email: false
    #recipients:
    #  - beast@gnome.org
    #on_success: never
    #on_failure: change
