# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

os:       linux
dist:     xenial
language: generic
services: docker

cache:
  directories:
    - ~/cache/
    - ~/beast/
    # We use $PIPELINE to carry cache context along job pipelines (workflows)
    # https://docs.travis-ci.com/user/caching/

# Job pipelines
jobs:
  include:

    # == 'Gcc' Pipeline ==
    # Build a highly optimized Gcc and upload it.
    - stage: Stage1
      name: "GCC-2 (autogen + appimage + check + bintray)"
      env: PIPELINE=Gcc
      before_install: |
        travis_retry git fetch --unshallow
      script: |
        misc/cibuild.sh gcc appimage check && {
          echo "$BINTRAY_API_KEY" > .bintray_api_key &&
          test "$TRAVIS_BRANCH^$TRAVIS_PULL_REQUEST" != "master^false" ||
          misc/cibuild.sh bintray ; }

    # == 'Linting' Pipeline ==
    # Generate all possible source code linting reports,
    # sort slow jobs into separate stages to avoid timeouts.
    - stage: Stage1
      name: "Linting-1 (autogen)"
      env: PIPELINE=clang
      before_install: |
        rm -v -rf ~/cache/* ~/beast && travis_retry git fetch --unshallow && cd .. && mv beast ~/
      install: |
        touch ~/cache/"$PIPELINE-$TRAVIS_BUILD_STAGE_NAME" && ls -l ~/cache/ && cd ~/beast/
      script: |
        misc/cibuild.sh quick
    - stage: Stage2
      name: "Linting-2 (cppcheck + scan-build)"
      env: PIPELINE=clang
      script: |
        misc/cibuild.sh cppcheck scan-build
    - stage: Stage3
      name: "Linting-3 (clang-tidy + listunused + listhacks + bintray)"
      env: PIPELINE=clang
      script: |
        misc/cibuild.sh clang-tidy &&
        echo "$BINTRAY_API_KEY" > .bintray_api_key &&
        misc/cibuild.sh listunused listhacks bintray

    # == Stage2 Fedora ==
    # Fedora build tests, runs *after* the 'appimage' succeeded
    - stage: Stage2
      name: "Fedora-27 (build + check)"
      env: PIPELINE=Fedora-27
      before_install: |
        travis_retry git fetch --unshallow
      script: |
        docker build --build-arg DIST=fedora:27 -f misc/Dockerfile-yum -t beast-fedora-27 .

    # == 'Asan' Pipeline ==
    # Run checks with asan turned on.
    - stage: Stage3
      name: "Asan (autogen + check)"
      env: PIPELINE=asan
      before_install: |
        travis_retry git fetch --unshallow
      before_script: |
        echo "$BINTRAY_API_KEY" > .bintray_api_key
      script: |
        misc/ciwitness.sh out/asan/build.log asan all check bintray

    # == 'Ubsan' Pipeline ==
    # Run checks with ubsan turned on.
    - stage: Stage3
      name: "Ubsan (autogen + check)"
      env: PIPELINE=ubsan
      before_install: |
        travis_retry git fetch --unshallow
      before_script: |
        echo "$BINTRAY_API_KEY" > .bintray_api_key
      script: |
        misc/ciwitness.sh out/ubsan/build.log ubsan all check bintray

  # == allow_failures ==
  allow_failures:
    - script: |
        docker build --build-arg DIST=fedora:27 -f misc/Dockerfile-yum -t beast-fedora-27 .
    - script: |
        misc/ciwitness.sh out/asan/build.log asan all check bintray
    - script: |
        misc/ciwitness.sh out/ubsan/build.log ubsan all check bintray

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
    on_success: always
    on_failure: always
    skip_join: true
  email: false
    #recipients:
    #  - beast@gnome.org
    #on_success: never
    #on_failure: change
