# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

os: linux
dist: trusty
sudo: required
services: docker
language: generic

env:
  # INTENT: gccbuild clangbuild package bintrayup
  matrix:
    - DIST="ubuntu:bionic"      INTENT="clangbuild,distcheck"
    - DIST="ubuntu:bionic"      INTENT="gccbuild"
    - DIST="ubuntu:artful"      INTENT="gccbuild"
    - DIST="ubuntu:xenial"      INTENT="gccbuild"
    # test upcoming releases and get new compiler warnings
    - DIST="ubuntu:cosmic"      INTENT="gccbuild"
    - DIST="debian:unstable"    INTENT="gccbuild"
    - DIST="debian:unstable"    INTENT="clangbuild"
matrix:
  allow_failures:
    - env: DIST="ubuntu:cosmic"      INTENT="gccbuild"
    - env: DIST="debian:unstable"    INTENT="gccbuild"
    - env: DIST="debian:unstable"    INTENT="clangbuild"
  fast_finish: true

before_install:
  # Show build setup
  - echo "INTENT=$INTENT DIST=$DIST"
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - python --version

install:
  # git describe requires complete history
  - travis_retry git fetch --unshallow

script:
  # Build inside docker container
  - TZ=GMT date
  - misc/dockerbuild.sh "$DIST" "$INTENT"
  - docker ps -a

after_success:
  - echo "OK, all done."

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
    on_success: always
    on_failure: always
    skip_join: true
  email: false
    #recipients:
    #  - beast@gnome.org
    #on_success: never
    #on_failure: change
